name: tiddlyroam
url: https://tiddlyroam.org
baseurl: ""
title: tiddlyroam
tagline: your open source external brain
description: "tiddlyroam is a free, open source alternative to Roam. It is a notetaking app that works the way your brain does: networked, personal and infinitely customisable." 
logo: assets/images/favicon.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag